### ISSUE TITLE
Jó napot

### ISSUE THREAD

**Issue by Rettend** [rkottra/BeleptetoRendszer1#1]
..Tanár Úr!

Látjuk, hogy elkezdett dolgozni a beléptető rendszeren, és felőlünk lenne igény, hogy hozzájáruljunk a fejlesztéséhez.
Mennyire fogadná szívesen a pull request-jeinket? Valamint esetleg egy kisebb Github Projectet is létrehozhatna, ahol rendszerezve számon tarthatnánk a még implementálandó részeket.

Üdv, 14A.

**Comment by rkottra** [comment]
Szia!

Nagyon kedvesek vagytok, de ennek a projektnek semmi köze nincs a beléptető
rendszerhez. Csak egy felnőttképzéses mintaprojekt kicsit elhibázott
névvel...

üdv
*Kottra Richárd*
*igazgatóhelyettes*
Győri Szakképzési Centrum Jedlik Ányos Gépipari és Informatikai
Technikum és Kollégium
9021 Győr, Szent István út 7.
+36 30 345 5102


Hegyi Áron Ferenc ***@***.***> ezt írta (időpont: 2022. nov.
8., K, 10:47):
